'use client';

import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import LoadingDumpling from '@/components/LoadingDumpling';
import RecipeEditor from '@/components/RecipeEditor';
import { StagingRecipe } from '@/types/staging';

export default function EditRecipePage() {
  const router = useRouter();
  const params = useParams();
  const recipeId = params.id as string;
  
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [stagingRecipe, setStagingRecipe] = useState<StagingRecipe | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!recipeId) return;
    
    const fetchRecipe = async () => {
      try {
        const res = await fetch(`/api/recipes/${recipeId}`);
        const data = await res.json();
        
        if (!res.ok) throw new Error(data.error || 'Failed to load recipe');
        
        // Transform API data to StagingRecipe format
        const recipe = data.recipe;
        const ingredients = data.ingredients || [];
        const steps = data.steps || [];

        const mappedRecipe: StagingRecipe = {
          id: recipe.id,
          title: recipe.title,
          summary: recipe.summary || '',
          source_url: recipe.source_url || '',
          chefs_notes: recipe.chefs_notes || [],
          estimated_final_weight_g: recipe.estimated_final_weight_g || undefined,
          yield_confidence: recipe.yield_confidence,
          extraction_model: recipe.extraction_model,
          yield_estimation_model: recipe.yield_estimation_model,
          
          ingredients: ingredients.map((ing: any) => ({
            id: ing.id || crypto.randomUUID(),
            name_raw: ing.name_raw || ing.name_normalized,
            name_normalized: ing.name_normalized,
            base_quantity_g: ing.base_quantity_g,
            role: ing.role || 'CONSUMABLE',
            state: ing.state,
            yield_factor: ing.yield_factor || 1,
            is_discrete: ing.is_discrete || false,
            dependency_role: ing.dependency_role || 'PASSENGER',
            density_confidence: ing.density_confidence || 'high',
            needs_review: false,
            is_to_taste: ing.is_to_taste || false
          })),
          
          steps: steps.map((step: any) => ({
            id: step.id || crypto.randomUUID(),
            order: step.order,
            instruction_raw: step.instruction_raw,
            constraint_tags: step.constraint_tags || []
          }))
        };

        setStagingRecipe(mappedRecipe);
      } catch (e: any) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    };

    fetchRecipe();
  }, [recipeId]);

  const handleSave = async (updatedRecipe: StagingRecipe) => {
    setSaving(true);
    try {
      // Transform StagingRecipe back to API format
      const payload = {
        recipe: {
          title: updatedRecipe.title,
          summary: updatedRecipe.summary,
          source_url: updatedRecipe.source_url,
          chefs_notes: updatedRecipe.chefs_notes,
          estimated_final_weight_g: updatedRecipe.estimated_final_weight_g,
          yield_confidence: updatedRecipe.yield_confidence
        },
        ingredients: updatedRecipe.ingredients.map(ing => ({
          // If it's a new ingredient (UUID generated on client), we might want to let backend handle ID or keep it?
          // Usually backend handles IDs for new items, but we'll send what we have.
          // If the ID is a UUID generated by us, the backend might treat it as new if it doesn't exist.
          // However, for updates, we should preserve IDs of existing items.
          id: ing.id, 
          name_normalized: ing.name_normalized,
          name_raw: ing.name_raw,
          base_quantity_g: ing.base_quantity_g,
          role: ing.role,
          state: ing.state,
          yield_factor: ing.yield_factor,
          is_discrete: ing.is_discrete,
          dependency_role: ing.dependency_role
        })),
        steps: updatedRecipe.steps.map((step, idx) => ({
          id: step.id,
          order: idx + 1, // Ensure order is correct
          instruction_raw: step.instruction_raw,
          constraint_tags: step.constraint_tags
        }))
      };

      const res = await fetch(`/api/recipes/${recipeId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Save failed');
      
      alert('Recipe updated successfully!');
      router.push('/recipes');
    } catch (e: any) {
      alert(`Error: ${e.message}`);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <LoadingDumpling message="Loading recipe..." size="medium" />;
  }

  if (error) {
    return (
      <div className="card" style={{ maxWidth: '600px', margin: '2rem auto' }}>
        <h2 className="mb-4">Error</h2>
        <p className="text-muted mb-4">{error}</p>
        <button className="btn btn-primary" onClick={() => router.push('/recipes')}>
          Back to Recipes
        </button>
      </div>
    );
  }

  if (!stagingRecipe) return null;

  return (
    <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
      <div style={{ marginBottom: '1rem' }}>
        <button 
          onClick={() => router.push('/recipes')}
          className="text-muted btn-link"
          style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer' }}
        >
          ← Back to Recipes
        </button>
      </div>
      
      <h1 className="mb-6">Edit Recipe</h1>
      
      <RecipeEditor
        recipe={stagingRecipe}
        onSave={handleSave}
        onCancel={() => router.push('/recipes')}
        isSaving={saving}
        saveLabel="Save Changes"
      />
    </div>
  );
}
